name: mc
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4
  - pandas
  - isort
  - mypy
  - python=3.13.3
  - pip
  - pytest
  - requests
  - pip:
      - black
      - bullet
      - mc-enchant
      - platformdirs
      - pytokens
