name: mc
channels:
  - defaults
dependencies:
  - beautifulsoup4=4.7.1
  - isort=4.3.19
  - lxml=4.3.3
  - mypy=0.701
  - pandas=0.24.2
  - pip=21.1
  - pytest=4.5.0
  - python=3.7.3
  - pip:
    - black==19.3b0
    - bullet==2.1.0
